name: Tarefa
description: Crie uma tarefa técnica para o projeto
title: "[TASK] "
labels: [task]
assignees: []
body:
  - type: textarea
    id: descricao
    attributes:
      label: Descrição da Tarefa
      description: Explique detalhadamente o que deve ser feito nesta tarefa.
      placeholder: Exemplo: Criar a tela de cadastro de produtos para a área administrativa do sistema.
      required: true

  - type: textarea
    id: requisitos
    attributes:
      label: Requisitos Técnicos e Dependências
      description: Quais tecnologias, bibliotecas, APIs ou outras tarefas estão envolvidas?
      placeholder: Exemplo: React, TailwindCSS, integração com API de produtos, depende da [TASK] Autenticação de Admin.
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist de Conclusão da Tarefa
      options:
        - label: Código desenvolvido
          required: true
        - label: Testado localmente (unidade, integração, manual)
          required: true
        - label: Commits enviados para a branch
          required: true
        - label: Pull Request (PR) criada e pronta para revisão
          required: true
    required: true
