name: Tarefa
description: Crie uma tarefa técnica para o projeto
title: "[Tarefa] "
labels: []
assignees: []
body:
  - type: textarea
    id: descricao
    attributes:
      label: Descrição
      description: Explique o que deve ser feito nesta tarefa.
      placeholder: Exemplo: Criar a tela de cadastro de produtos para admin...
      required: true

  - type: textarea
    id: requisitos
    attributes:
      label: Requisitos técnicos
      description: Tecnologias ou bibliotecas envolvidas nesta tarefa.
      placeholder: Exemplo: React, Tailwind, Axios...
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist de conclusão
      options:
        - label: Código escrito
        - label: Testado localmente
        - label: Commit enviado
        - label: PR criada
